In [1]:
import pandas as pd
import numpy as np

Thanks to Kriti Mahajan. This table was developed with study type features extracted from the meta data.
Code found here: https://colab.research.google.com/drive/1lay-yWJ5ohN94lQLHYIxtWMuDWtCRGy0#scrollTo=N-IhAeEkcxDe

In [2]:
mf = pd.read_csv("metadata_features.csv")
mf

,Unnamed: 0,paper_id,title,abstract,publish_time,authors,url,Statistical Methods,statistical_method_details,Study Type,study_type_details,results,coronavirus,fatality,sample_size,paper_focus,variables_controlled_for
0,0,zjufx4fo,Sequence requirements for RNA strand transfer ...,Nidovirus subgenomic mRNAs contain a leader se...,2001-12-17,"Pasternak, Alexander O.; van den Born, Erwin; ...",http://europepmc.org/articles/pmc125340?pdf=re...,[],NaN,"['genom', 'mutagenesis']",Nidovirus subgenomic mRNAs contain a leader se...,Here we present results of a comprehensive co-...,NaN,NaN,NaN,NaN,NaN
1,1,ymceytj3,"Crystal structure of murine sCEACAM1a[1,4]: a ...",CEACAM1 is a member of the carcinoembryonic an...,2002-05-01,"Tan, Kemin; Zelus, Bruce D.; Meijers, Rob; Liu...",http://europepmc.org/articles/pmc125375?pdf=re...,[],NaN,['protein'],We discuss the structural basis of virus recep...,Here we report the crystal structure of solubl...,NaN,NaN,NaN,NaN,NaN
2,2,wzj2glte,Synthesis of a novel hepatitis C virus protein...,Hepatitis C virus (HCV) is an important human ...,2001-07-16,"Xu, Zhenming; Choi, Jinah; Yen, T.S.Benedict; ...",https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...,[],NaN,"['protein', 'genom']","Its RNA genome codes for a polyprotein, which ...",NaN,NaN,NaN,NaN,NaN,NaN
3,3,2sfqsfm1,Structure of coronavirus main proteinase revea...,The key enzyme in coronavirus polyprotein proc...,2002-07-01,"Anand, Kanchan; Palm, Gottfried J.; Mesters, J...",http://europepmc.org/articles/pmc126080?pdf=re...,['model'],Molecular modelling and mutagenesis data impli...,"['protein', 'mutagenesis']",The key enzyme in coronavirus polyprotein proc...,The study illustrates that RNA viruses have ev...,NaN,NaN,NaN,NaN,NaN
4,4,i0zym7iq,Discontinuous and non-discontinuous subgenomic...,"Arteri-, corona-, toro- and roniviruses are ev...",2002-12-01,"van Vliet, A.L.W.; Smits, S.L.; Rottier, P.J.M...",http://europepmc.org/articles/pmc136939?pdf=re...,[],NaN,['genom'],"During infection, multiple subgenomic (sg) mRN...",We show that BEV mRNAs 3–5 lack a leader seque...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56640,56640,rn4gm3sc,Structure-Based Stabilization of Non-native Pr...,[Image: see text] Structure-based stabilizatio...,2020-02-27,"Lin, Shan-Meng; Lin, Shih-Chao; Hsu, Jia-Ning;...",https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7...,[],NaN,['protein'],[Image: see text] Structure-based stabilizatio...,NaN,"Here, we identified a non-native interaction i...",NaN,NaN,NaN,NaN
56641,56641,l5oecoot,Immunomodulators as an antimicrobial tool,The spectrum of infectious diseases has shifte...,2006-10-31,"Pirofski, Liise-anne; Casadevall, Arturo",https://doi.org/10.1016/j.mib.2006.08.004,[' tool'],"However, to date only a few immunomodulators h...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
56642,56642,i4acg2ex,Discourses of disease: Representations of tube...,Abstract This paper critically examines the wa...,2008-02-29,"Lawrence, Jody; Kearns, Robin A.; Park, Julie;...",https://doi.org/10.1016/j.socscimed.2007.10.015,[],NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
56643,56643,rve0w3dg,Equine Infectious Anemia,This article describes clinical signs and tran...,1993-08-31,"Sellon, Debra Clabough",https://doi.org/10.1016/s0749-0739(17)30399-1,[],NaN,"['review', 'clinical']",This article describes clinical signs and tran...,NaN,NaN,NaN,NaN,NaN,NaN
56644,56644,ut7dlyh8,A duplex real-time reverse transcriptase polym...,Abstract A duplex TaqMan real-time reverse tra...,2009-10-31,"Wang, Heng; Nattanmai, Seela; Kramer, Laura D....",https://doi.org/10.1016/j.diagmicrobio.2009.07...,[],NaN,"['protein', 'genetic']",The targets selected for the assay were the se...,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
list(mf)

['Unnamed: 0',
 'paper_id',
 'title',
 'abstract',
 'publish_time',
 'authors',
 'url',
 'Statistical Methods',
 'statistical_method_details',
 'Study Type',
 'study_type_details',
 'results',
 'coronavirus',
 'fatality',
 'sample_size',
 'paper_focus',
 'variables_controlled_for']

In [4]:
mf['Study Type'].value_counts()

[]                                                                                       26228
['protein']                                                                               6699
['clinical']                                                                              4373
['review']                                                                                2533
['genom']                                                                                 1251
                                                                                         ...
['review', 'cross section', 'cross sectional', 'clinical']                                   1
['retrospective study', 'prospective study', 'clinical']                                     1
['genom', 'genetic', 'life cycle', 'clinical']                                               1
['prospective cohort', 'prospective cohort', 'prospective observational', 'clinical']        1
['protein', 'mutagenesis', 'genetic', 'experimental']                                        1
Name: Study Type, Length: 607, dtype: int64

Initially, will work with this and see F1 score. Will then create own features by traditional feature engineering and reverse engineering to get cleanest features set possible. Caveat with this preliminary feature set is that when [] is taken out, 46% of the metadata is not accounted for (no study type key words). Can remedy this through changing n-gram feature-set to be more specific and relevant/feature engineering.

## Features Preprocessing

In [5]:
features = mf.drop(columns = ['Unnamed: 0',
 'title',
 'abstract',
 'publish_time',
 'authors',
 'url',
 'Statistical Methods',
 'statistical_method_details',
 'study_type_details',
 'results',
 'coronavirus',
 'fatality',
 'sample_size',
 'paper_focus',
 'variables_controlled_for'])
features

       paper_id                  Study Type
0      zjufx4fo    ['genom', 'mutagenesis']
1      ymceytj3                 ['protein']
2      wzj2glte        ['protein', 'genom']
3      2sfqsfm1  ['protein', 'mutagenesis']
4      i0zym7iq                   ['genom']
...         ...                         ...
56640  rn4gm3sc                 ['protein']
56641  l5oecoot                          []
56642  i4acg2ex                          []
56643  rve0w3dg      ['review', 'clinical']
56644  ut7dlyh8      ['protein', 'genetic']

[56645 rows x 2 columns]

In [6]:
features.isnull().sum()

paper_id      0
Study Type    0
dtype: int64

In [54]:
#Get rid of rows with empty lists (STRING TYPE) since void of study type features.
# test2 =  features[features['Study Type'].astype(bool)]
# test2
to_drop = ['[]']
features = features[~features['Study Type'].isin(to_drop)]
features

       paper_id                  Study Type
0      zjufx4fo    ['genom', 'mutagenesis']
1      ymceytj3                 ['protein']
2      wzj2glte        ['protein', 'genom']
3      2sfqsfm1  ['protein', 'mutagenesis']
4      i0zym7iq                   ['genom']
...         ...                         ...
56638  jna496x7                 ['protein']
56639  4jg4t8po                 ['protein']
56640  rn4gm3sc                 ['protein']
56643  rve0w3dg      ['review', 'clinical']
56644  ut7dlyh8      ['protein', 'genetic']

[30417 rows x 2 columns]

## Joining feature set to label set (Kaggle for now)

In order to attach study type features to labels, need to use CoronaWhy annotations dataset that has cord_uid that matches with paper_id from above as well as sha that matches with id in label dataset.

In [44]:
get_cord_uid = pd.read_csv("Study_Design_Annotation_Snapshot_4_12_20.csv")
labels = pd.read_csv("design.csv")

In [47]:
list(mf_cordid)

['paper_id',
 'Study Type',
 'Assignee',
 'cord_uid',
 'sha',
 'title',
 'url',
 'in silico',
 'in vitro',
 'in vivo',
 'Systematic reivew or meta-analysis of RCTs',
 'RCT',
 'Non-randomized controlled trial',
 'Comparative study with a concurrent or historical comparator (cohort studies, case-control studies, 2 or more single-arm studies, or interrupted time series with a control group)',
 'Descriptive study without a comparator (single-arm pre-post studies, case series, case reports)',
 'Systematic review or meta-analysis of studies other than RCTs',
 'Other ',
 'General Notes']

In [55]:
feat_cordid = features.merge(get_cord_uid, how='inner', left_on='paper_id', right_on='cord_uid')
feat_cordid = feat_cordid.drop(columns = ['Assignee',
 'title',
 'url',
 'in silico',
 'in vitro',
 'in vivo',
 'Systematic reivew or meta-analysis of RCTs',
 'RCT',
 'Non-randomized controlled trial',
 'Comparative study with a concurrent or historical comparator (cohort studies, case-control studies, 2 or more single-arm studies, or interrupted time series with a control group)',
 'Descriptive study without a comparator (single-arm pre-post studies, case series, case reports)',
 'Systematic review or meta-analysis of studies other than RCTs',
 'Other ',
 'General Notes'] )
feat_cordid

,paper_id,Study Type,cord_uid,sha
0,lwla5ugt,"['genom', 'bioinformatics']",lwla5ugt,8970ef10049816050cb1bc5fbf600865a5996ad4
1,gdsfkw1b,"['protein', 'review']",gdsfkw1b,8d7400a2b387820cd391d7df8194642e50402a0c
2,e1iaiwc6,['survey'],e1iaiwc6,eddc547cbba693715e4fd55e6a946e8ec7d96bc2
3,o088rxb5,['clinical'],o088rxb5,9f63ebfaab049c0968d72166761217b3aaa1fe00
4,icp9d998,['clinical'],icp9d998,8c640872048570b0a671ec08c83ef6cbebcdd78e
...,...,...,...,...
595,f7i4lq2w,"['genetic', 'clinical']",f7i4lq2w,450921cad3744aa651260fdd482038f546992999
596,hwt1foyu,['protein'],hwt1foyu,ce0f694c2a6f8568c566118e14bef4c1898957f6
597,c9zya2t7,['protein'],c9zya2t7,2b7cc2e066ab4f8252246b530424d878b260b108
598,437zx0xr,['survey'],437zx0xr,9da58647ca34a42efcf47cec929b7163a808a65d
599,0y5jaf1m,['protein'],0y5jaf1m,60a342d1b18b2059aa722f46cc9f8b9770b6919c

In [57]:
labels_merge = feat_cordid.merge(labels, how='inner', left_on='sha', right_on='id')
labels_merge

,paper_id,Study Type,cord_uid,sha,label,id
0,7n75m669,['genetic'],7n75m669,5e9ccecdd40825f5c30da3a900fc5cf1b063b47d,8,5e9ccecdd40825f5c30da3a900fc5cf1b063b47d
1,ie3msqwt,['genetic'],ie3msqwt,5b15c62ee761d6eefeb7d2ef023f804bfdc41edc,9,5b15c62ee761d6eefeb7d2ef023f804bfdc41edc
2,u1m7yr8f,"['questionnaire', 'survey', 'cross-sectional']",u1m7yr8f,eac85c85c3a2ac1d3fe53e1e3b3fee98f52527ad,7,eac85c85c3a2ac1d3fe53e1e3b3fee98f52527ad
3,a27prjq9,['review'],a27prjq9,4bc6ead9368ec84dba7c56b78624f681293e568b,7,4bc6ead9368ec84dba7c56b78624f681293e568b
4,9vrny92m,['review'],9vrny92m,d7d62e768f4a8eb40ba522eca28e173e5d53cbbc,4,d7d62e768f4a8eb40ba522eca28e173e5d53cbbc

In [58]:
list(labels_merge)

['paper_id', 'Study Type', 'cord_uid', 'sha', 'label', 'id']

In [59]:
final = labels_merge.drop(columns = ['cord_uid', 'sha', 'id'])
final

   paper_id                                      Study Type  label
0  7n75m669                                     ['genetic']      8
1  ie3msqwt                                     ['genetic']      9
2  u1m7yr8f  ['questionnaire', 'survey', 'cross-sectional']      7
3  a27prjq9                                      ['review']      7
4  9vrny92m                                      ['review']      4

Only 5 results. This is a sad. It is due to new dataset being larger (10,000 more papers). So there are going to be more dissimilar paper_ids.  In order to limit dataset reduction, need to see if featuers dataframe can be remade with longer(sha?) paper_id in order to match with labels dataframe directly.

If this does not work out, will then need to synthesize labels. So to summarize:
1. Max out matches between feature set and label set
2. Feature engineer via revising ngram list/reverse engineer
3. Synthetic labels for mutlilabels annotations

### Trying direct merge with mf and kaggle label set via sha.

In [69]:
mf2 = pd.read_csv('metadata_features-2.csv')
mf2

,Unnamed: 0,paper_id,sha,title,abstract,publish_time,authors,url,Statistical Methods,statistical_method_details,Study Type,study_type_details,results,coronavirus,fatality,sample_size,paper_focus,variables_controlled_for
0,0,zjufx4fo,b2897e1277f56641193a6db73825f707eed3e4c9,Sequence requirements for RNA strand transfer ...,Nidovirus subgenomic mRNAs contain a leader se...,2001-12-17,"Pasternak, Alexander O.; van den Born, Erwin; ...",http://europepmc.org/articles/pmc125340?pdf=re...,[],NaN,['mutagenesis'],Here we present results of a comprehensive co-...,Here we present results of a comprehensive co-...,NaN,NaN,NaN,NaN,NaN
1,1,ymceytj3,e3d0d482ebd9a8ba81c254cc433f314142e72174,"Crystal structure of murine sCEACAM1a[1,4]: a ...",CEACAM1 is a member of the carcinoembryonic an...,2002-05-01,"Tan, Kemin; Zelus, Bruce D.; Meijers, Rob; Liu...",http://europepmc.org/articles/pmc125375?pdf=re...,[],NaN,[],NaN,Here we report the crystal structure of solubl...,NaN,NaN,NaN,NaN,NaN
2,2,wzj2glte,00b1d99e70f779eb4ede50059db469c65e8c1469,Synthesis of a novel hepatitis C virus protein...,Hepatitis C virus (HCV) is an important human ...,2001-07-16,"Xu, Zhenming; Choi, Jinah; Yen, T.S.Benedict; ...",https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...,[],NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2sfqsfm1,cf584e00f637cbd8f1bb35f3f09f5ed07b71aeb0,Structure of coronavirus main proteinase revea...,The key enzyme in coronavirus polyprotein proc...,2002-07-01,"Anand, Kanchan; Palm, Gottfried J.; Mesters, J...",http://europepmc.org/articles/pmc126080?pdf=re...,['model'],Molecular modelling and mutagenesis data impli...,['mutagenesis'],Molecular modelling and mutagenesis data impli...,The study illustrates that RNA viruses have ev...,NaN,NaN,NaN,NaN,NaN
4,4,i0zym7iq,dde02f11923815e6a16a31dd6298c46b109c5dfa,Discontinuous and non-discontinuous subgenomic...,"Arteri-, corona-, toro- and roniviruses are ev...",2002-12-01,"van Vliet, A.L.W.; Smits, S.L.; Rottier, P.J.M...",http://europepmc.org/articles/pmc136939?pdf=re...,[],NaN,[],NaN,We show that BEV mRNAs 3–5 lack a leader seque...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59125,59125,pwq5gir9,20f185b11fa23da8938efb5c839c6c078c66f1e9,Cutting-Edge Infectious Disease Diagnostics wi...,"Three recent Science articles (Chen et al., 20...",2018-06-13,"Chiu, Charles",https://doi.org/10.1016/j.chom.2018.05.016,[],NaN,['clinical'],"Three recent Science articles (Chen et al., 20...",NaN,NaN,NaN,NaN,NaN,NaN
59126,59126,3racv2qe,e84532333db8f219f20ae0a8fe18130c0d010b04,Intranasal administration of oxytocin: Behavio...,Abstract The intranasal (IN-) administration o...,2013-09-30,"Veening, Jan G.; Olivier, Berend",https://doi.org/10.1016/j.neubiorev.2013.04.012,[],NaN,['review'],The present review explores our current knowle...,Only very recently in a microdialysis study in...,NaN,NaN,NaN,NaN,NaN
59127,59127,jngto9kv,31105078a2953217223699d09c6a80d0f5edfdf6,Infecciones virales graves en pacientes inmuno...,Resumen Los virus tienen un papel importante d...,2011-04-30,"Díaz, A.; Zaragoza, R.; Granada, R.; Salavert, M.",https://doi.org/10.1016/j.medin.2011.01.001,[],NaN,['review'],A review of the literature has been performed ...,NaN,NaN,"Furthermore, ventilator-associated pneumonia (...",NaN,NaN,NaN
59128,59128,td0776wj,b1f977d58a0eba25acdee5912ef71c372b0632de,"18 Omics, Bioinformatics, and Infectious Disea...",Bioinformatics and the ‘omics’ studies are rap...,2011-12-31,"Paszkiewicz, Konrad H.; Giezen, Mark van der",https://doi.org/10.1016/b978-0-12-384890-1.000...,"['sequencing', 'methods']","In addition, we provide an overview of methods...",['bioinformatics'],Bioinformatics and the ‘omics’ studies are rap...,NaN,NaN,NaN,NaN,NaN,NaN
59129,59129,jxbr6hbk,4eb170db0dd666fc669649d0e6b15e513b6598d6; 9403...,Identifying spatio-temporal dynamics of Ebola ...,Containing the recent West African outbreak of...,2017-11-29,"Gustafson, Kyle B.; Proctor, Joshua L.",https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...,"['model', 'forecast', ' tool']",Despite recent progress in analysing and model...,['genetic'],Calibrated to phylogenetic linkages of virus g...,"Consistent with other investigations, our resu...",NaN,NaN,NaN,NaN,NaN

In [72]:
list(mf2)

['Unnamed: 0',
 'paper_id',
 'sha',
 'title',
 'abstract',
 'publish_time',
 'authors',
 'url',
 'Statistical Methods',
 'statistical_method_details',
 'Study Type',
 'study_type_details',
 'results',
 'coronavirus',
 'fatality',
 'sample_size',
 'paper_focus',
 'variables_controlled_for']

In [73]:
features2 = mf2.drop(columns = ['Unnamed: 0',
 'title',
 'abstract',
 'publish_time',
 'authors',
 'url',
 'Statistical Methods',
 'statistical_method_details',
 'study_type_details',
 'results',
 'coronavirus',
 'fatality',
 'sample_size',
 'paper_focus',
 'variables_controlled_for'])
features2

,paper_id,sha,Study Type
0,zjufx4fo,b2897e1277f56641193a6db73825f707eed3e4c9,['mutagenesis']
1,ymceytj3,e3d0d482ebd9a8ba81c254cc433f314142e72174,[]
2,wzj2glte,00b1d99e70f779eb4ede50059db469c65e8c1469,[]
3,2sfqsfm1,cf584e00f637cbd8f1bb35f3f09f5ed07b71aeb0,['mutagenesis']
4,i0zym7iq,dde02f11923815e6a16a31dd6298c46b109c5dfa,[]
...,...,...,...
59125,pwq5gir9,20f185b11fa23da8938efb5c839c6c078c66f1e9,['clinical']
59126,3racv2qe,e84532333db8f219f20ae0a8fe18130c0d010b04,['review']
59127,jngto9kv,31105078a2953217223699d09c6a80d0f5edfdf6,['review']
59128,td0776wj,b1f977d58a0eba25acdee5912ef71c372b0632de,['bioinformatics']
59129,jxbr6hbk,4eb170db0dd666fc669649d0e6b15e513b6598d6; 9403...,['genetic']

In [74]:
to_drop = ['[]']
features2 = features2[~features2['Study Type'].isin(to_drop)]
features2

,paper_id,sha,Study Type
0,zjufx4fo,b2897e1277f56641193a6db73825f707eed3e4c9,['mutagenesis']
3,2sfqsfm1,cf584e00f637cbd8f1bb35f3f09f5ed07b71aeb0,['mutagenesis']
6,gi6uaa83,8ae137c8da1607b3a8e4c946c07ca8bda67f88ac,"['genetic', 'histories']"
7,0m32ecnu,23bc55d6f63fab18b02004483888db2b6a0bfa48,['genetic']
10,fy4w7xz8,0104f6ceccf92ae8567a0102f89cbb976969a774,['genetic']
...,...,...,...
59125,pwq5gir9,20f185b11fa23da8938efb5c839c6c078c66f1e9,['clinical']
59126,3racv2qe,e84532333db8f219f20ae0a8fe18130c0d010b04,['review']
59127,jngto9kv,31105078a2953217223699d09c6a80d0f5edfdf6,['review']
59128,td0776wj,b1f977d58a0eba25acdee5912ef71c372b0632de,['bioinformatics']
59129,jxbr6hbk,4eb170db0dd666fc669649d0e6b15e513b6598d6; 9403...,['genetic']

In [94]:
labels_merge2 = features2.merge(labels, how='inner', left_on='sha', right_on='id')
labels_merge2

,paper_id,sha,Study Type,label,id
0,47ema2dq,6a3fa8ed278df0d05c5e009521de11c72308f60b,['review'],1,6a3fa8ed278df0d05c5e009521de11c72308f60b
1,ub9dtgup,78326020e9f7cd75415a3a192729ccf0c0930281,"['genetic', 'questionnaire']",8,78326020e9f7cd75415a3a192729ccf0c0930281
2,8f0pn321,NaN,['survey'],2,NaN
3,xavtxl4m,NaN,['survey'],2,NaN
4,ciuhyhb8,NaN,['clinical'],2,NaN
...,...,...,...,...,...
3660,l4649du3,bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e,['clinical'],2,bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e
3661,3vpoxfnv,eb720970f362e4416b73393f230c8606c837c6dc,['clinical'],10,eb720970f362e4416b73393f230c8606c837c6dc
3662,p8vhi6d9,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb,['experimental'],2,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb
3663,a6i73v0o,95d9bac431797e2cf8b7294a648ceec3bd50c84b,"['questionnaire', 'survey', 'cross-sectional']",7,95d9bac431797e2cf8b7294a648ceec3bd50c84b
3664,nbbcacy4,76edb6d0bd7c47765d3a89032aa610f410506988,['case study'],9,76edb6d0bd7c47765d3a89032aa610f410506988

Check for duplicates. (There are probably duplicates because sha is not unique identifier but indicator of change)

In [95]:
labels_merge2.sha.nunique()

429

In [96]:
labels_merge2.paper_id.nunique()

3665

There are 429 shared papers between sha and id. However, what produces the 3665 results for labels_merge2 is the paper_id column that there are  sha dupilicates. So if we remove duplicates, will get 429 results for modeling.

In [97]:
labels_merge2 = labels_merge2.drop_duplicates(subset=['sha'])

final = pd.merge(labels_merge2, labels, how='inner', left_on='sha', right_on='id')
final

,paper_id,sha,Study Type,label_x,id_x,label_y,id_y
0,47ema2dq,6a3fa8ed278df0d05c5e009521de11c72308f60b,['review'],1,6a3fa8ed278df0d05c5e009521de11c72308f60b,1,6a3fa8ed278df0d05c5e009521de11c72308f60b
1,ub9dtgup,78326020e9f7cd75415a3a192729ccf0c0930281,"['genetic', 'questionnaire']",8,78326020e9f7cd75415a3a192729ccf0c0930281,8,78326020e9f7cd75415a3a192729ccf0c0930281
2,8f0pn321,NaN,['survey'],2,NaN,2,NaN
3,9trzqzep,eb4b8f43f68db5e493984b7e4e56d9f804d7e885,"['questionnaire', 'cross-sectional']",9,eb4b8f43f68db5e493984b7e4e56d9f804d7e885,9,eb4b8f43f68db5e493984b7e4e56d9f804d7e885
4,7n75m669,5e9ccecdd40825f5c30da3a900fc5cf1b063b47d,['genetic'],8,5e9ccecdd40825f5c30da3a900fc5cf1b063b47d,8,5e9ccecdd40825f5c30da3a900fc5cf1b063b47d
...,...,...,...,...,...,...,...
425,l4649du3,bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e,['clinical'],2,bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e,2,bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e
426,3vpoxfnv,eb720970f362e4416b73393f230c8606c837c6dc,['clinical'],10,eb720970f362e4416b73393f230c8606c837c6dc,10,eb720970f362e4416b73393f230c8606c837c6dc
427,p8vhi6d9,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb,['experimental'],2,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb,2,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb
428,a6i73v0o,95d9bac431797e2cf8b7294a648ceec3bd50c84b,"['questionnaire', 'survey', 'cross-sectional']",7,95d9bac431797e2cf8b7294a648ceec3bd50c84b,7,95d9bac431797e2cf8b7294a648ceec3bd50c84b
429,nbbcacy4,76edb6d0bd7c47765d3a89032aa610f410506988,['case study'],9,76edb6d0bd7c47765d3a89032aa610f410506988,9,76edb6d0bd7c47765d3a89032aa610f410506988

This is a really small dataset. So next step is to augment dataset with CoronaWhy dataset as well as Pubmed annotations.

So need to augment annotations dataset (To Kaggle's add, CoronaWhy's) by using Christine Chen's mapping.

In [89]:
labels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188 entries, 0 to 1187
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   1188 non-null   int64
 1   id      1187 non-null   object
dtypes: int64(1), object(1)
memory usage: 18.7+ KB

In [90]:
labels2 = pd.read_csv('design-2.csv')
labels2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1438 entries, 0 to 1437
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   1438 non-null   int64
 1   id      1438 non-null   object
dtypes: int64(1), object(1)
memory usage: 22.6+ KB

In [131]:
final2 = pd.merge(features2, labels2, how='inner', left_on='sha', right_on='id')
final2

,paper_id,sha,Study Type,label,id
0,47ema2dq,6a3fa8ed278df0d05c5e009521de11c72308f60b,['review'],1,6a3fa8ed278df0d05c5e009521de11c72308f60b
1,9trzqzep,eb4b8f43f68db5e493984b7e4e56d9f804d7e885,"['questionnaire', 'cross-sectional']",8,eb4b8f43f68db5e493984b7e4e56d9f804d7e885
2,hnu8gw6w,2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9,"['time series', 'clinical']",5,2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9
3,5ulk3euw,9f7ed2037968c63fa97eb6fc7c35e9738a654541,['cross-sectional'],7,9f7ed2037968c63fa97eb6fc7c35e9738a654541
4,loowpch7,de707f97b534ca340482600ed1f008b20d7b1b8e,"['prospective cohort', 'prospective cohort']",4,de707f97b534ca340482600ed1f008b20d7b1b8e
...,...,...,...,...,...
493,dycx8i7h,2d0d272a793b99ef896547024c51f486e9552e5a,['genetic'],0,2d0d272a793b99ef896547024c51f486e9552e5a
494,p8vhi6d9,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb,['experimental'],2,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb
495,a6i73v0o,95d9bac431797e2cf8b7294a648ceec3bd50c84b,"['questionnaire', 'survey', 'cross-sectional']",7,95d9bac431797e2cf8b7294a648ceec3bd50c84b
496,i2vg8zqc,e9dfbc4084497e74dcaf6bd9c1dbde2b0fb70802,"['experimental', 'clinical']",0,e9dfbc4084497e74dcaf6bd9c1dbde2b0fb70802
497,nbbcacy4,76edb6d0bd7c47765d3a89032aa610f410506988,['case study'],8,76edb6d0bd7c47765d3a89032aa610f410506988

In [132]:
final2 = final2.drop(columns = ['id'])
final2

,paper_id,sha,Study Type,label
0,47ema2dq,6a3fa8ed278df0d05c5e009521de11c72308f60b,['review'],1
1,9trzqzep,eb4b8f43f68db5e493984b7e4e56d9f804d7e885,"['questionnaire', 'cross-sectional']",8
2,hnu8gw6w,2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9,"['time series', 'clinical']",5
3,5ulk3euw,9f7ed2037968c63fa97eb6fc7c35e9738a654541,['cross-sectional'],7
4,loowpch7,de707f97b534ca340482600ed1f008b20d7b1b8e,"['prospective cohort', 'prospective cohort']",4
...,...,...,...,...
493,dycx8i7h,2d0d272a793b99ef896547024c51f486e9552e5a,['genetic'],0
494,p8vhi6d9,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb,['experimental'],2
495,a6i73v0o,95d9bac431797e2cf8b7294a648ceec3bd50c84b,"['questionnaire', 'survey', 'cross-sectional']",7
496,i2vg8zqc,e9dfbc4084497e74dcaf6bd9c1dbde2b0fb70802,"['experimental', 'clinical']",0
497,nbbcacy4,76edb6d0bd7c47765d3a89032aa610f410506988,['case study'],8

69 more Kaggle labels with updated Kaggle dataset merged with Kriti's dataset.

Also, need to use updated CoronaWhy dataset.

In [133]:
cw_labels = pd.read_csv('CoY_newlist.csv')

In [134]:
list(cw_labels)

['Assignee',
 'cord_uid',
 'sha',
 'title',
 'url',
 'Computational ',
 'Experimental-in vitro',
 'Experimental-in vivo',
 'Systematic review and/or meta-analysis',
 'Clinical-interventional',
 'Clinical-interventional.1',
 'Clinical-observational',
 'Clinical-observational.1',
 'Systematic review and/or meta-analysis ',
 'Other',
 'General Notes']

In [135]:
cw_labels = cw_labels.drop(columns = ['Other', 'General Notes'])

In [136]:
#Rename/Clean-up labels
cw_labels = cw_labels.rename(columns={'Computational ': 'Computational', 'Experimental-in vitro' : 'Experimental - in vitro', 'Experimental-in vivo' : 'Experimental - in vivo', 'Clinical-interventional.1' : 'Clinical-interventional', 'Clinical-observational.1' : 'Clinical-observational', 'Systematic review and/or meta-analysis ' : 'Systematic review and/or meta-analysis'})

In [137]:
list(cw_labels)

['Assignee',
 'cord_uid',
 'sha',
 'title',
 'url',
 'Computational',
 'Experimental - in vitro',
 'Experimental - in vivo',
 'Systematic review and/or meta-analysis',
 'Clinical-interventional',
 'Clinical-interventional',
 'Clinical-observational',
 'Clinical-observational',
 'Systematic review and/or meta-analysis']

Mapping Kaggle to CoY_newlist annotations.

In [138]:
final2.explode('label')
final2['label'].unique()

array([1, 8, 5, 7, 4, 2, 9, 6, 0, 3])

In [139]:
dic_map={
         1:'Systematic review and/or meta-analysis',
         2:'Clinical-interventional',
         3:'Clinical-interventional',
         4:'Clinical-observational',
         5:'Clinical-observational',
         6:'Clinical-observational',
         7:'Clinical-observational',
         8:'Clinical-observational',
         9:'Computational',
         0:'Other'
        }

In [140]:
final2['mapped'] = final2.apply(lambda x: dic_map[x.label], axis = 1) 
final2.head()

,paper_id,sha,Study Type,label,mapped
0,47ema2dq,6a3fa8ed278df0d05c5e009521de11c72308f60b,['review'],1,Systematic review and/or meta-analysis
1,9trzqzep,eb4b8f43f68db5e493984b7e4e56d9f804d7e885,"['questionnaire', 'cross-sectional']",8,Clinical-observational
2,hnu8gw6w,2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9,"['time series', 'clinical']",5,Clinical-observational
3,5ulk3euw,9f7ed2037968c63fa97eb6fc7c35e9738a654541,['cross-sectional'],7,Clinical-observational
4,loowpch7,de707f97b534ca340482600ed1f008b20d7b1b8e,"['prospective cohort', 'prospective cohort']",4,Clinical-observational

## Remove all rows that have 'Other' in Mapped column

In [141]:
final2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 498 entries, 0 to 497
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   paper_id    498 non-null    object
 1   sha         498 non-null    object
 2   Study Type  498 non-null    object
 3   label       498 non-null    int64
 4   mapped      498 non-null    object
dtypes: int64(1), object(4)
memory usage: 23.3+ KB

In [142]:
final2 = final2[final2.label != 0]
final2

,paper_id,sha,Study Type,label,mapped
0,47ema2dq,6a3fa8ed278df0d05c5e009521de11c72308f60b,['review'],1,Systematic review and/or meta-analysis
1,9trzqzep,eb4b8f43f68db5e493984b7e4e56d9f804d7e885,"['questionnaire', 'cross-sectional']",8,Clinical-observational
2,hnu8gw6w,2afcf2ab2330cb56ec493f82d87fa0c5b5f076e9,"['time series', 'clinical']",5,Clinical-observational
3,5ulk3euw,9f7ed2037968c63fa97eb6fc7c35e9738a654541,['cross-sectional'],7,Clinical-observational
4,loowpch7,de707f97b534ca340482600ed1f008b20d7b1b8e,"['prospective cohort', 'prospective cohort']",4,Clinical-observational
...,...,...,...,...,...
490,l4649du3,bb3bf36ce2af876dcbf80b6cf3598e4421c98b3e,['clinical'],2,Clinical-interventional
491,3vpoxfnv,eb720970f362e4416b73393f230c8606c837c6dc,['clinical'],9,Computational
494,p8vhi6d9,f778c6317cdc3e2c4aa7a8c7734fa13da10723eb,['experimental'],2,Clinical-interventional
495,a6i73v0o,95d9bac431797e2cf8b7294a648ceec3bd50c84b,"['questionnaire', 'survey', 'cross-sectional']",7,Clinical-observational
497,nbbcacy4,76edb6d0bd7c47765d3a89032aa610f410506988,['case study'],8,Clinical-observational

100 less annotations is a huge drop.

In [143]:
pubmed_labels = pd.read_csv('metadata_extra_info_from_pubmed_db.csv')
pubmed_labels

,is_rct,is_systematic_reivew,is_review,is_meta_analysis,is_observational_study,is_case_series,is_clincal_trial,cord_uid,pubmed_id
0,False,False,False,False,False,False,False,zjufx4fo,11742998
1,False,False,False,False,False,False,False,ymceytj3,11980704
2,False,False,False,False,False,False,False,wzj2glte,11447125
3,False,False,False,False,False,False,False,2sfqsfm1,12093723
4,False,False,False,False,False,False,False,i0zym7iq,12456663
...,...,...,...,...,...,...,...,...,...
57361,False,False,False,False,False,False,False,rn4gm3sc,32105468
57362,False,False,True,False,False,False,False,l5oecoot,16931122
57363,False,False,False,False,False,False,False,i4acg2ex,18035462
57364,False,False,True,False,False,False,False,rve0w3dg,8395326
57365,False,False,False,False,False,False,False,ut7dlyh8,19748425

MAPPING SCHEME

Mapping Kaggle to new list
1 - Systematic review -> Systematic review and/or meta-analysis
2 - Randomized control trial -> Clinical-interventional
3 - Non-randomized trial -> Clinical - interventional
4 - Prospective observational -> Clinical -observational
5 - Time-to-event analysis -> Clinical-observational
6 - Retrospective observational -> Clinical-observational
7 - Cross-sectional -> Clinical-observational
8 - Case series -> Clinical-observational
9 - Modeling -> Computational
0 - Other -> drop
5:48
Mapping our data to new list
In silico -> Computational
In vitro  -> Experimental - in vitro
In vivo -> Experimental - in vivo
Systematic review or meta-analysis of RCTs -> Systematic review and/or meta-analysis
Randomized controlled trial -> Clinical-interventional
Non-randomized controlled trial -> Clinical-interventional
Comparative study  -> Clinical -observational	
Descriptive study  -> Clinical -observational
Systematic review or meta-analysis of studies other than RCTs -> Systematic review and/or meta-analysis
Other (commentary, editorial, non-systematic review, expert opinion) -> Other
(edited)
5:53
Also @Dan Sosa and I are doing quality check on our labels so there might be an updated version coming up in the next few days. A major update will be an addition of a new category “Review”, which deals with non-systematic literature reviews
5:55
FYI, here’s the new list of categories
Computational studies (simulation, modeling)
Experimental studies (animals, cells, perhaps similar to molecular studies in  Artur’s list)
2.1 In vitro
2.2 In vivo
3. Clinical studies (human subjects)
3.1 Interventional studies (RCT, CCT, Phase 1-4 clinical trials)
3.2 Observational studies (prospective/retrospective cohorts, case series, case-control, cross sectional, case series, case reports, etc, perhaps similar to epidemiological studies in the list)
4. Review (literature reviews, non-systematic). -> We are generating this
5. Systematic review and/or meta-analysis
6. Non-clinical observational studies (aggregated demographic characteristics, humidity, pollution, population density and temperature) ->won’t be able to classify this with our data or with Kaggle, so please ignore it for now
7. Other